---
format: pdf
margin-left: 2.5cm
margin-right: 2.5cm
margin-top: 2cm
margin-bottom: 4.5cm
header-includes:
  - \usepackage{enumitem,fancyhdr}
  - \usepackage[font=small,labelfont=bf,tableposition=top]{caption}
  - \DeclareCaptionLabelFormat{andtable}{#1~#2  \&  \tablename~\thetable}
  - \setlength{\parindent}{0.0in}
  - \setlength{\parskip}{0.05in}
  - \pagestyle{fancyplain}
  - \headheight 35pt
  - \lhead{Friday, May 12, 2023}
  - \chead{\textbf{\Large Lab 9}}
  - \rhead{DATA 119 \\ Spring 2023}
  - \lfoot{}
  - \cfoot{}
  - \rfoot{\small\thepage}
  - \headsep 1.5em
urlcolor: blue
---

<!-- \thispagestyle{fancy} -->

```{r, setup, include=FALSE}
library(kableExtra)
library(latex2exp)
library(reticulate)

knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small",   # slightly smaller font for code
  warning = FALSE, message = FALSE, 
  fig.align = 'center', fig.height = 2.5) 
 
set.seed(108)
```


\section*{Problem One: Goodreads Data}

For this lab, you will use a dataset that I have been creating on [goodreads.com](goodreads.com). Goodreads allows you to keep track of and rate books that you have or would like to read. It also collects and aggregates user data. You should have two tables--one with my personal data in the goodreads_library_export_050823.sql file, and another called locations.sql. 

\begin{enumerate}[label=\alph*.]
  \item Download the two .sql files. Using the online interpreter \href{https://sqliteonline.com/}{https://sqliteonline.com/}, upload them both and rename them to \texttt{nussbaum\_goodreads} and \texttt{locations}.
  \item Write a query that will allow you to view all of the columns in \texttt{nussbaum\_goodreads}. How many rows are there? How many variables are there? Read through the columns to try and get a sense of what each variable means.
  \item What kind of binding do I read most frequently, according to this database?
  \item What book did I add to the database most recently?
  \item Is there a publisher that I seem to enjoy more than others, based on my ratings? For ease of answering, sort the output by some reasonable value.
  \item The results of the previous query should seem suspicious to you. Suppose you want to answer the same question--what publisher do I enjoy the most--but considering only publishers that I have read from at least five times.
  \item A friend of mine has a personal rule--he will not read books that are rated as less than a 3.8 on Goodreads. What are some books that I have read that I could recommend to him? What is the most popular book that I have read that I could recommend to him?
  \item What are the longest and shortest books I have read?
  \item Why might the short book from the previous question have 0 pages? Are there more books that have 0 pages?
  \item What is the average page length of an audiobook? Make sure to consider all possible bindings. 
  \item Write a query that will allow you to view all of the columns in \texttt{locations}. How many rows are there? How many variables are there? Read through the columns to try and get a sense of what each variable means.
  \item How many of these books take place in each continent?
  \item How many books are on both lists? It may help to abbreviate the tables in your query.
  \item How many books have I read that take place in Illinois? It may help to create a new table. 
  \item What is one of the books I liked best that took place in England, and what is the book that I liked least that took place in England? 
  \item What is the most highly rated book that takes place in each of Argentina, France, Germany, Japan, Italy, and Switzerland? 
  \item Write a query that you think answers an interesting question about this dataset. Post the question in the thread on Ed so that your classmates can get more practice!
\end{enumerate}
